In [1]:
#importo le librerie necessarie alla manipolazione dei datasets
import pandas as pd
import numpy as np

#carico il dataset 'dati-classifica-sanremo-1951-2023.xlsx' in un dataframe
df_classifica = pd.read_excel('C:\\Users\\matte\\Downloads\\dati-finalassignment\\dati-classifica-sanremo-1951-2023.xlsx', sheet_name='Sheet1')

#elimino la colonna 'Unnamed: 0'
df_classifica = df_classifica.drop(columns=['Unnamed: 0'])

#rinomino la colonna 'anno' in 'Anno'
df_classifica = df_classifica.rename(columns={'anno':'Anno'})

#rimuovo tutti i duplicati
df_classifica = df_classifica.drop_duplicates()

# rimuovo tutte le righe che hanno valori nulli nella colonna 'Canzone'
df_classifica = df_classifica.dropna(subset=['Canzone'])

#rimuovo tutti gli spazi iniziali e finali di tutte le stringhe
df_classifica = df_classifica.map(lambda x: x.strip() if type(x)==str else x)

#trasformo i valori della colonna 'Anno' in tipo 'data' e la rinomino in 'Data'
df_classifica['Anno'] = pd.to_datetime(df_classifica['Anno'], format='%Y')
df_classifica = df_classifica.rename(columns={'Anno':'Data'})

#in una nuova colonna 'Anno' estraggo l'anno dalla colonna 'Data' come valore intero
df_classifica['Anno'] = df_classifica['Data'].dt.year

#stampo il dataframe
df_classifica

,Posizione,Interprete,Canzone,Data,Autori,Anno
0,1º,Nilla Pizzi,Grazie dei fiori,1951-01-01,Gian Carlo Testoni e Mario Panzeri,1951
1,2º,Nilla Pizzi e Achille Togliani,La luna si veste d'argento,1951-01-01,Biri,1951
2,3º,Achille Togliani,Serenata a nessuno,1951-01-01,Walter Colì,1951
3,F,Achille Togliani e Duo Fasano,Al mercato di Pizzighettone,1951-01-01,Aldo Locatelli,1951
4,F,Nilla Pizzi e Achille Togliani,Eco tra gli abeti,1951-01-01,Enzo Bonagura,1951
...,...,...,...,...,...,...
1658,24º,Olly,Polvere,2023-01-01,"Olly, E. Lovito e J. Boverod",2023
1659,25º,Anna Oxa,Sali (canto dell'anima),2023-01-01,"A. Oxa, F. Bianconi, Kaballà e F. Zanotti",2023
1660,26º,Will,Stupido,2023-01-01,"Will, S. Cremonini e A. Pugliese",2023
1661,27º,Shari,Egoista,2023-01-01,"Shari, M. Pisciottu, L. Fenudi e R. Puddu",2023
1662,28º,Sethu,Cause perse,2023-01-01,M. De Lauri e G. De Lauri,2023

In [2]:
# Aggiungo una nuova colonna 'Canzone_Unica' che combina il nome della canzone con l'anno di rilascio, per avere un identificativo unico per ogni canzone
df_classifica['Canzone_Unica'] = df_classifica['Canzone'] + ' (' + df_classifica['Anno'].astype(str) + ')'

#Rimuovi tutti i duplicati dalla colonna 'Canzone_Unica'
df_classifica = df_classifica.drop_duplicates(subset=['Canzone_Unica'])

# Visualizza il dataframe aggiornato
df_classifica

,Posizione,Interprete,Canzone,Data,Autori,Anno,Canzone_Unica
0,1º,Nilla Pizzi,Grazie dei fiori,1951-01-01,Gian Carlo Testoni e Mario Panzeri,1951,Grazie dei fiori (1951)
1,2º,Nilla Pizzi e Achille Togliani,La luna si veste d'argento,1951-01-01,Biri,1951,La luna si veste d'argento (1951)
2,3º,Achille Togliani,Serenata a nessuno,1951-01-01,Walter Colì,1951,Serenata a nessuno (1951)
3,F,Achille Togliani e Duo Fasano,Al mercato di Pizzighettone,1951-01-01,Aldo Locatelli,1951,Al mercato di Pizzighettone (1951)
4,F,Nilla Pizzi e Achille Togliani,Eco tra gli abeti,1951-01-01,Enzo Bonagura,1951,Eco tra gli abeti (1951)
...,...,...,...,...,...,...,...
1658,24º,Olly,Polvere,2023-01-01,"Olly, E. Lovito e J. Boverod",2023,Polvere (2023)
1659,25º,Anna Oxa,Sali (canto dell'anima),2023-01-01,"A. Oxa, F. Bianconi, Kaballà e F. Zanotti",2023,Sali (canto dell'anima) (2023)
1660,26º,Will,Stupido,2023-01-01,"Will, S. Cremonini e A. Pugliese",2023,Stupido (2023)
1661,27º,Shari,Egoista,2023-01-01,"Shari, M. Pisciottu, L. Fenudi e R. Puddu",2023,Egoista (2023)
1662,28º,Sethu,Cause perse,2023-01-01,M. De Lauri e G. De Lauri,2023,Cause perse (2023)

In [3]:
#nel df_classifica
#nella colonna autori, sostituisco con una virgola, se presenti, i caratteri che dividono i vari autori
df_classifica['Autori'] = df_classifica['Autori'].str.replace(' ed ', " , ")
df_classifica['Autori'] = df_classifica['Autori'].str.replace(' e ', " , ")
df_classifica['Autori'] = df_classifica['Autori'].str.replace(' & ', " , ")
df_classifica['Autori'] = df_classifica['Autori'].str.replace(' & ', " , ")
df_classifica['Autori'] = df_classifica['Autori'].str.replace(' feat. ', " , ")
df_classifica['Autori'] = df_classifica['Autori'].str.replace(' feat ', " , ")
df_classifica['Autori'] = df_classifica['Autori'].str.replace(' ft. ', " , ")
df_classifica['Autori'] = df_classifica['Autori'].str.replace(' ft ', " , ")
df_classifica['Autori'] = df_classifica['Autori'].str.replace(' con ', " , ")

#creo un nuovo dataframe 'Autori' con la colonna 'Autori' splittata in base alla virgola
df_autori = df_classifica['Autori'].str.split(',', expand=True)
df_autori

#rinomino tutte le colonne presenti nel dataframe 'Autori' aggiungendo prima del numero presente la parola 'Autore'
for i in range(len(df_autori.columns)):
    df_autori = df_autori.rename(columns={i:'Autore_'+str(i+1)})

##aggiungo come prima colonna il nome della canzone
df_autori.insert(0, 'Canzone', df_classifica['Canzone_Unica'])
df_autori

#rimuovo gli spazi iniziali e finali presenti nelle stringhe
df_autori = df_autori.apply(lambda x: x.str.strip() if x.dtype == "object" else x)

#stampo il dataframe
df_autori

,Canzone,Autore_1,Autore_2,Autore_3,Autore_4,Autore_5,Autore_6,Autore_7,Autore_8
0,Grazie dei fiori (1951),Gian Carlo Testoni,Mario Panzeri,None,None,None,None,None,None
1,La luna si veste d'argento (1951),Biri,None,None,None,None,None,None,None
2,Serenata a nessuno (1951),Walter Colì,None,None,None,None,None,None,None
3,Al mercato di Pizzighettone (1951),Aldo Locatelli,None,None,None,None,None,None,None
4,Eco tra gli abeti (1951),Enzo Bonagura,None,None,None,None,None,None,None
...,...,...,...,...,...,...,...,...,...
1658,Polvere (2023),Olly,E. Lovito,J. Boverod,None,None,None,None,None
1659,Sali (canto dell'anima) (2023),A. Oxa,F. Bianconi,Kaballà,F. Zanotti,None,None,None,None
1660,Stupido (2023),Will,S. Cremonini,A. Pugliese,None,None,None,None,None
1661,Egoista (2023),Shari,M. Pisciottu,L. Fenudi,R. Puddu,None,None,None,None
1662,Cause perse (2023),M. De Lauri,G. De Lauri,None,None,None,None,None,None

In [4]:
#nel df_autori voglio visualizzare tutte le righe che hanno valore non nullo nella colonna 'Autore_8'
df_autori[df_autori['Autore_8'].notnull()]

,Canzone,Autore_1,Autore_2,Autore_3,Autore_4,Autore_5,Autore_6,Autore_7,Autore_8
1651,Furore (2023),J. Ettorre,A. La Cava,P. Iezzi,C. Iezzi,F. Mercuri,G. Cremona,L. Grillotti,E. Maimone

In [5]:
#creo  e stampo un dataframe 'autori_canzone' con la colonna 'Autore' che contiene tutti gli autori presenti nel dataframe 'df_autori' accoppiati ad ogni canzone che hanno scritto
autori_canzone = pd.melt(df_autori, id_vars=['Canzone'], value_vars=['Autore_1', 'Autore_2', 'Autore_3', 'Autore_4', 'Autore_5', 'Autore_6', 'Autore_7', 'Autore_8'], value_name='Autore')
autori_canzone = autori_canzone.drop(columns=['variable'])
autori_canzone = autori_canzone.dropna(subset=['Autore'])
autori_canzone = autori_canzone.drop_duplicates()
autori_canzone = autori_canzone.reset_index(drop=True)
autori_canzone

                                                Canzone              Autore
0                               Grazie dei fiori (1951)  Gian Carlo Testoni
1                     La luna si veste d'argento (1951)                Biri
2                             Serenata a nessuno (1951)         Walter Colì
3                    Al mercato di Pizzighettone (1951)      Aldo Locatelli
4                              Eco tra gli abeti (1951)       Enzo Bonagura
...                                                 ...                 ...
3835  Bentivoglio Angelina (Kon tutto il mio amaro) ...         G. Facchini
3836                                  Combat pop (2021)        M. Romagnoli
3837                              Un bel viaggio (2023)        D. Silvestri
3838                                      Furore (2023)        L. Grillotti
3839                                      Furore (2023)          E. Maimone

[3840 rows x 2 columns]

In [6]:
#nel df_classifica
#nella colonna Interprete, sostituisco con una virgola, se presenti, i caratteri che dividono i vari interpreti

df_classifica['Interprete'] = df_classifica['Interprete'].str.replace(' ed ', " , ")
df_classifica['Interprete'] = df_classifica['Interprete'].str.replace(' e ', " , ")
df_classifica['Interprete'] = df_classifica['Interprete'].str.replace(' & ', " , ")
df_classifica['Interprete'] = df_classifica['Interprete'].str.replace(' - ', " , ")
df_classifica['Interprete'] = df_classifica['Interprete'].str.replace(' feat. ', " , ")
df_classifica['Interprete'] = df_classifica['Interprete'].str.replace(' feat ', " , ")
df_classifica['Interprete'] = df_classifica['Interprete'].str.replace(' ft. ', " , ")
df_classifica['Interprete'] = df_classifica['Interprete'].str.replace(' ft ', " , ")
df_classifica['Interprete'] = df_classifica['Interprete'].str.replace(' con ', " , ")


#creo un nuovo dataframe 'Interprete' con la colonna 'Interprete' splittata in base alla virgola
df_interpreti = df_classifica['Interprete'].str.split(',', expand=True)

#rinomino tutte le colonne presenti nel dataframe 'Interprete' aggiungendo prima del numero presente la parola 'Interprete'
for i in range(len(df_interpreti.columns)):
    df_interpreti = df_interpreti.rename(columns={i:'Interprete_'+str(i+1)})

#aggiungo come prima colonna il nome della canzone
df_interpreti.insert(0, 'Canzone', df_classifica['Canzone_Unica'])

#rimuovo gli spazi iniziali e finali presenti nelle stringhe
df_interpreti = df_interpreti.apply(lambda x: x.str.strip() if x.dtype == "object" else x)

#stampo il dataframe
df_interpreti

,Canzone,Interprete_1,Interprete_2,Interprete_3,Interprete_4,Interprete_5
0,Grazie dei fiori (1951),Nilla Pizzi,None,None,None,None
1,La luna si veste d'argento (1951),Nilla Pizzi,Achille Togliani,None,None,None
2,Serenata a nessuno (1951),Achille Togliani,None,None,None,None
3,Al mercato di Pizzighettone (1951),Achille Togliani,Duo Fasano,None,None,None
4,Eco tra gli abeti (1951),Nilla Pizzi,Achille Togliani,None,None,None
...,...,...,...,...,...,...
1658,Polvere (2023),Olly,None,None,None,None
1659,Sali (canto dell'anima) (2023),Anna Oxa,None,None,None,None
1660,Stupido (2023),Will,None,None,None,None
1661,Egoista (2023),Shari,None,None,None,None
1662,Cause perse (2023),Sethu,None,None,None,None

In [7]:
#nel df_interprete voglio visualizzare tutte le righe che hanno valore non nullo nella colonna 'Interprete_5'
df_interpreti[df_interpreti['Interprete_5'].notnull()]

,Canzone,Interprete_1,Interprete_2,Interprete_3,Interprete_4,Interprete_5
82,Canto nella valle (1955),Natalino Otto,Trio Aurora,Bruno Pallesi,Nuccia Bongiovanni,Radio Boys
90,Era un omino (1955),Clara Jaione,Radio Boys,Nella Colombo,Bruno Rosettani,Trio Aurora
92,Il primo viaggio (1955),Bruno Pallesi,Nuccia Bongiovanni,Bruno Rosettani,Nella Colombo,Trio Aurora
119,Casetta in Canadà (1957),Carla Boni,Gino Latilla,Duo Fasano,Gloria Christian,Poker di Voci
125,Le trote blu (1957),Carla Boni,Duo Fasano,Gloria Christian,Natalino Otto,Poker di Voci

In [8]:
#creo e stampo un dataframe 'interpreti_canzone' con la colonna 'Interprete' che contiene tutti gli interpreti presenti nel dataframe 'df_interpreti' accoppiati ad ogni canzone che hanno cantato
interpreti_canzone = pd.melt(df_interpreti, id_vars=['Canzone'], value_vars=['Interprete_1', 'Interprete_2', 'Interprete_3', 'Interprete_4', 'Interprete_5'], value_name='Interprete')
interpreti_canzone = interpreti_canzone.drop(columns=['variable'])
interpreti_canzone = interpreti_canzone.dropna(subset=['Interprete'])
interpreti_canzone = interpreti_canzone.drop_duplicates()
interpreti_canzone = interpreti_canzone.reset_index(drop=True)
interpreti_canzone

                                 Canzone        Interprete
0                Grazie dei fiori (1951)       Nilla Pizzi
1      La luna si veste d'argento (1951)       Nilla Pizzi
2              Serenata a nessuno (1951)  Achille Togliani
3     Al mercato di Pizzighettone (1951)  Achille Togliani
4               Eco tra gli abeti (1951)       Nilla Pizzi
...                                  ...               ...
2272            Canto nella valle (1955)        Radio Boys
2273                 Era un omino (1955)       Trio Aurora
2274             Il primo viaggio (1955)       Trio Aurora
2275            Casetta in Canadà (1957)     Poker di Voci
2276                 Le trote blu (1957)     Poker di Voci

[2277 rows x 2 columns]

In [9]:
#creo una nuova tabella facendo una inner join tra il dataframe 'df_autori' e il dataframe 'df_interpreti' sulla colonna 'Canzone'
df_autori_interpreti = pd.merge(df_autori, df_interpreti, on='Canzone', how='inner')

#inserisco la colonna 'Anno' dopo la colonna 'Canzone'
df_autori_interpreti.insert(1, 'Anno', df_classifica['Anno'])

#stampo il dataframe
df_autori_interpreti

,Canzone,Anno,Autore_1,Autore_2,Autore_3,Autore_4,Autore_5,Autore_6,Autore_7,Autore_8,Interprete_1,Interprete_2,Interprete_3,Interprete_4,Interprete_5
0,Grazie dei fiori (1951),1951,Gian Carlo Testoni,Mario Panzeri,None,None,None,None,None,None,Nilla Pizzi,None,None,None,None
1,La luna si veste d'argento (1951),1951,Biri,None,None,None,None,None,None,None,Nilla Pizzi,Achille Togliani,None,None,None
2,Serenata a nessuno (1951),1951,Walter Colì,None,None,None,None,None,None,None,Achille Togliani,None,None,None,None
3,Al mercato di Pizzighettone (1951),1951,Aldo Locatelli,None,None,None,None,None,None,None,Achille Togliani,Duo Fasano,None,None,None
4,Eco tra gli abeti (1951),1951,Enzo Bonagura,None,None,None,None,None,None,None,Nilla Pizzi,Achille Togliani,None,None,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1658,Polvere (2023),2023,Olly,E. Lovito,J. Boverod,None,None,None,None,None,Olly,None,None,None,None
1659,Sali (canto dell'anima) (2023),2023,A. Oxa,F. Bianconi,Kaballà,F. Zanotti,None,None,None,None,Anna Oxa,None,None,None,None
1660,Stupido (2023),2023,Will,S. Cremonini,A. Pugliese,None,None,None,None,None,Will,None,None,None,None
1661,Egoista (2023),2023,Shari,M. Pisciottu,L. Fenudi,R. Puddu,None,None,None,None,Shari,None,None,None,None
1662,Cause perse (2023),2023,M. De Lauri,G. De Lauri,None,None,None,None,None,None,Sethu,None,None,None,None

In [10]:
#per ciascun valore del dataframe 'df_autori_interpreti' splitto in base al carattere ' '
df_autori_interpreti_check = df_autori_interpreti.apply(lambda x: x.str.split(' ') if x.dtype == "object" else x)

#definisco una funzione 'check_match' che restituisce True se un autore è anche un interprete, altrimenti restituisce False
def check_match(row):
    autori = [item for sublist in row[['Autore_1', 'Autore_2', 'Autore_3', 'Autore_4', 'Autore_5', 'Autore_6', 'Autore_7', 'Autore_8']].dropna() for item in sublist]
    interpreti = [item for sublist in row[['Interprete_1', 'Interprete_2', 'Interprete_3', 'Interprete_4', 'Interprete_5']].dropna() for item in sublist]
    return any(autore in interpreti for autore in autori)

#applico la funzione 'check_match' al dataframe 'df_autori_interpreti_check' e salvo il risultato nella colonna 'Cantautore'
df_autori_interpreti['Cantautore'] = df_autori_interpreti_check.apply(check_match, axis=1)

#Nella colonna 'Cantautore' sostituisco i valori True con 'Cantautore' e i valori False con 'Cantante'
df_autori_interpreti['Cantautore'] = df_autori_interpreti['Cantautore'].replace({True:'Cantautore', False:'Cantante'})

#stampo il dataframe
df_autori_interpreti

,Canzone,Anno,Autore_1,Autore_2,Autore_3,Autore_4,Autore_5,Autore_6,Autore_7,Autore_8,Interprete_1,Interprete_2,Interprete_3,Interprete_4,Interprete_5,Cantautore
0,Grazie dei fiori (1951),1951,Gian Carlo Testoni,Mario Panzeri,None,None,None,None,None,None,Nilla Pizzi,None,None,None,None,Cantante
1,La luna si veste d'argento (1951),1951,Biri,None,None,None,None,None,None,None,Nilla Pizzi,Achille Togliani,None,None,None,Cantante
2,Serenata a nessuno (1951),1951,Walter Colì,None,None,None,None,None,None,None,Achille Togliani,None,None,None,None,Cantante
3,Al mercato di Pizzighettone (1951),1951,Aldo Locatelli,None,None,None,None,None,None,None,Achille Togliani,Duo Fasano,None,None,None,Cantante
4,Eco tra gli abeti (1951),1951,Enzo Bonagura,None,None,None,None,None,None,None,Nilla Pizzi,Achille Togliani,None,None,None,Cantante
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1658,Polvere (2023),2023,Olly,E. Lovito,J. Boverod,None,None,None,None,None,Olly,None,None,None,None,Cantautore
1659,Sali (canto dell'anima) (2023),2023,A. Oxa,F. Bianconi,Kaballà,F. Zanotti,None,None,None,None,Anna Oxa,None,None,None,None,Cantautore
1660,Stupido (2023),2023,Will,S. Cremonini,A. Pugliese,None,None,None,None,None,Will,None,None,None,None,Cantautore
1661,Egoista (2023),2023,Shari,M. Pisciottu,L. Fenudi,R. Puddu,None,None,None,None,Shari,None,None,None,None,Cantautore
1662,Cause perse (2023),2023,M. De Lauri,G. De Lauri,None,None,None,None,None,None,Sethu,None,None,None,None,Cantante

In [11]:
#aggiungo al 'df_autori_interpreti' la colonna 'Posizione' presente nel dataframe 'df_classifica' e la inserisco dopo la colonna 'Canzone'
df_autori_interpreti.insert(2, 'Posizione', df_classifica['Posizione'])

#stampo il dataframe
df_autori_interpreti

,Canzone,Anno,Posizione,Autore_1,Autore_2,Autore_3,Autore_4,Autore_5,Autore_6,Autore_7,Autore_8,Interprete_1,Interprete_2,Interprete_3,Interprete_4,Interprete_5,Cantautore
0,Grazie dei fiori (1951),1951,1º,Gian Carlo Testoni,Mario Panzeri,None,None,None,None,None,None,Nilla Pizzi,None,None,None,None,Cantante
1,La luna si veste d'argento (1951),1951,2º,Biri,None,None,None,None,None,None,None,Nilla Pizzi,Achille Togliani,None,None,None,Cantante
2,Serenata a nessuno (1951),1951,3º,Walter Colì,None,None,None,None,None,None,None,Achille Togliani,None,None,None,None,Cantante
3,Al mercato di Pizzighettone (1951),1951,F,Aldo Locatelli,None,None,None,None,None,None,None,Achille Togliani,Duo Fasano,None,None,None,Cantante
4,Eco tra gli abeti (1951),1951,F,Enzo Bonagura,None,None,None,None,None,None,None,Nilla Pizzi,Achille Togliani,None,None,None,Cantante
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1658,Polvere (2023),2023,24º,Olly,E. Lovito,J. Boverod,None,None,None,None,None,Olly,None,None,None,None,Cantautore
1659,Sali (canto dell'anima) (2023),2023,25º,A. Oxa,F. Bianconi,Kaballà,F. Zanotti,None,None,None,None,Anna Oxa,None,None,None,None,Cantautore
1660,Stupido (2023),2023,26º,Will,S. Cremonini,A. Pugliese,None,None,None,None,None,Will,None,None,None,None,Cantautore
1661,Egoista (2023),2023,27º,Shari,M. Pisciottu,L. Fenudi,R. Puddu,None,None,None,None,Shari,None,None,None,None,Cantautore
1662,Cause perse (2023),2023,28º,M. De Lauri,G. De Lauri,None,None,None,None,None,None,Sethu,None,None,None,None,Cantante

In [12]:
# salvo come file .csv i dataframe necessari alla stesura del report su Google Looker Studio

df_classifica.to_csv('C:\\Users\\matte\\Downloads\\dati-finalassignment\\df_classifica.csv', index=False)
interpreti_canzone.to_csv('C:\\Users\\matte\\Downloads\\dati-finalassignment\\interpreti_canzone.csv', index=False)
autori_canzone.to_csv('C:\\Users\\matte\\Downloads\\dati-finalassignment\\autori_canzone.csv', index=False)
df_autori_interpreti.to_csv('C:\\Users\\matte\\Downloads\\dati-finalassignment\\df_autori_interpreti.csv', index=False)